version: '3'
services:
  anytore-frontend:
    image: anytore/frontend:latest
    ports:
      - '8081:80'
    networks:
      - anytore-external-net

networks:
  anytore-external-net:
    driver: bridge
