version: '3'
services:
  anytore-frontend:
    image: anytore/frontend:latest
    ports:
      - '8081:80'
    networks:
      - anytore-net
    restart: always
    volumes:
      - ./admin-htpasswd:/etc/nginx/.htpasswd

networks:
  anytore-net:
    driver: bridge
